---
# TODO: implement synchronization logic
- name: Create group for remote servers.
  import_playbook: playbooks/create_group.yml

- name: Look for "File To Sync" on romote servers.
  import_playbook: playbooks/check_is_file_exists.yml

- name: Assert that "File To Sync" was founded.
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Assert that "File To Sync" was founded or finish play if not.
      assert:
        that: '"DUMMY_HOLDER" in hostvars'
        fail_msg: '"File To Sync" was not founded on any host.'
        success_msg: '"File To Sync" was founded.'

- name: Enable ssh on remote servers
  import_playbook: playbooks/enable_ssh.yml

- name: Synchronize.
  hosts: remote_servers
  gather_facts: true
  tasks:
    - name: Generic question with multiple different responses.
      remote_user: root
      expect:
        command: "rsync -avzh root@{{ hostvars['DUMMY_HOLDER']['file_holder_ip'] | string }}:{{ fileToSync }} {{ fileToSync }}"
        responses:
          'Are you sure you want to continue connecting (yes/no/[fingerprint])?': 'yes'
      when: not file_presence