---
- name: Synchronize fileToSync
  hosts: all
  vars:
    - tmp_local_path: "{{ playbook_dir }}/{{ fileToSync}}"
    - file_presence: false

  pre_tasks:
    - assert:
        that:
          - fileToSync is defined
      run_once: true

    - name: Add dummy host for variable holding.
      add_host:
        name: "DUMMY_HOLDER"
        file_founded_somewhere: false
      run_once: true

    - name: Clear tmp directory.
      local_action: file path="{{ tmp_local_path }}" state=absent
      run_once: true

    - name: Get stat of fileToSync
      stat:
        path: "{{ fileToSync }}"
      register: stat_exec

    - name: Set information about fileToSync presence.
      set_fact:
        file_presence: true
      when: stat_exec.stat.exists == true

    - name: Fetch fileToSync.
      fetch: 
        src: "{{ fileToSync }}"
        dest: "{{ tmp_local_path }}"
        validate_checksum: false
        flat: true
      when: stat_exec.stat.exists == true and hostvars['DUMMY_HOLDER']['file_founded_somewhere'] == false
      
    - name: Set information about fileToSync presence to DUMMY_HOLDER.
      set_fact:
        file_founded_somewhere: true
      delegate_to: DUMMY_HOLDER
      delegate_facts: true
      when: stat_exec.stat.exists == true and hostvars['DUMMY_HOLDER']['file_founded_somewhere'] == false

  tasks:
    - name: Assert that fileToSync was founded or finish play if not.
      assert:
        that: hostvars['DUMMY_HOLDER']['file_founded_somewhere']
        fail_msg: '"File To Sync" was not founded on any host.'
        success_msg: '"File To Sync" was founded.'
      run_once: true

  post_tasks:
    - name: Copy fileToSync to servers.
      copy:
        src: "{{ tmp_local_path }}"
        dest: "{{ fileToSync }}"
      when: file_presence == false